version: "3"
services:
  schema-registry:
    image: confluentinc/cp-schema-registry
    network_mode: "host"
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://127.0.0.1:9092